### ISSUE TITLE
Can not use with slim-flash package

### ISSUE THREAD

**Issue by codewithelvin** [bryanjhv/slim-session#47] opened 2020-04-02 21:00 UTC
I have a piece of code in view container
```php
$view->getEnvironment()->addGlobal('flash', $container->get('flash'));
```
without `session_start()` in `index.php` file I get this error:
```
faultCode0faultStringFatal error:Uncaught RuntimeException: Flash messages middleware failed. Session not found. in /shared/httpd/oss/htdocs/vendor/slim/flash/src/Messages.php:66 
Stack trace: 
#0 /shared/httpd/oss/htdocs/init/container.php(55): Slim\Flash\Messages->__construct() 
#1 [internal function]: {closure}() 
#2 /shared/httpd/oss/htdocs/vendor/php-di/invoker/src/Invoker.php(82): call_user_func_array(Object(Closure), Array) 
#3 /shared/httpd/oss/htdocs/vendor/php-di/php-di/src/Definition/Resolver/FactoryResolver.php(80): Invoker\Invoker->call(Object(Closure), Array) 
#4 /shared/httpd/oss/htdocs/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(64): DI\Definition\Resolver\FactoryResolver->resolve(Object(DI\Definition\FactoryDefinition), Array) 
#5 /shared/httpd/oss/htdocs/vendor/php-di/php-di/src/Container.php(380): DI\Definition\Resolver\ResolverDispatcher->resolve(Object(DI\Definition\FactoryDefinition), Array) 
#6 /shared/httpd/oss/htdocs/vendor/php-di/php-di/src/Container.php(138): DI\Container->resolveDefinition(Object(D in /shared/httpd/oss/htdocs/vendor/slim/flash/src/Messages.php on line 66
```
But I want to use only `bryanjhv/slim-session` to control my session in project. Any real implementation of code?

**Edited**

Here are details required:

_composer.json_
```json
"slim/slim": "4.*",
"bryanjhv/slim-session": "^4.0",
"slim/flash": "^0.4.0",
...
```

_container.php_
```
$container->set('flash', function () {
    return new Messages();
});

$container->set('view', function ($container) {
    $loader = new FilesystemLoader('views');
    $view = new Twig($loader, ['cache' => $container->get('settings')['views']['cache']]);
    $view->getEnvironment()->addGlobal('flash', $container->get('flash'));
    return $view;
});
```
_middleware.php_
```php
$app->add(new \Slim\Middleware\Session([
    'name' => 'sso_session',
    'autorefresh' => true,
    'lifetime' => '1 hour'
]));

$app->add(TwigMiddleware::createFromContainer($app));
```

Now using devilbox containsers with:

- PHP (7.2.15)
- Apache (2.2.34)
- MariaDB (10.0.34)

**Comment by bryanjhv** [comment] 2020-04-02 23:32
First at all, thanks for reporting this.

Second, please just open one issue, not 5 like you did.

Then, please include a bit more code and info, specifically:
- composer.json `require` (to see versions you are using).
- PHP code where you register both middleware (Flash & Session).
- Server environment (PHP version, operating system, etc).

For what I see at:
- http://www.slimframework.com/docs/v3/features/flash.html
- https://github.com/slimphp/Slim-Flash/blob/0.4.0/src/Messages.php#L65-L67

The issue is that `session_start` (which this module calls) has to be called first.
So you might solve it by registering SlimSession first, then the Flash module.

**Comment by codewithelvin** [comment] 2020-04-03 16:30
Any updates on current issue?

**Comment by bryanjhv** [comment] 2020-04-03 20:34
I don't see where is the Flash package being registered.

**Comment by codewithelvin** [comment] 2020-04-04 05:06
That's all codes I have in my project. Now I have updated my question text above and added `conaitener.php`. The fact is that when I add `session_start()` in my `index.php` file everything works fine. But this breaks the logic of your code.

**Comment by bryanjhv** [comment] 2020-04-04 19:16
Where are ```container.php``` and ```middleware.php``` glued together? Please provide a complete sample code, so I can test it and determine which is the real problem and maybe give a solution.

Anyway, it looks like this is a problem with the way SlimFlash is designed, by checking for ```$_SESSION``` at instantiation. SlimSession is a middleware, which means it'll be called for each request so I don't intend to call ```session_start()``` at instantiation time.

SlimFlash accepts a ```$storage``` parameter, and it can be an ```ArrayAccess```, which ```SlimSession\Helper``` provides, you might have luck passing an instance of that to the constructor.

Said all that, there's nothing I can do regarding the (possible) bad design of that package, so I'll close this. If you need additional help that doesn't involve changing something in this package, feel free to comment, maybe there's a way to solve this.

**Closed as completed by bryanjhv** 2020-04-04 19:16 UTC
