### ISSUE TITLE
Notice: session_start(): ps_files_cleanup_dir: opendir(/var/lib/php/sessions) failed: Permission denied (13) 

### ISSUE THREAD

**Issue by alesanchezr** [bryanjhv/slim-session#19] opened 2017-07-03 22:53 UTC
Is giving me an error when I try to use it:
Notice: session_start(): ps_files_cleanup_dir: opendir(/var/lib/php/sessions) failed: Permission denied (13) in /home/ubuntu/workspace/vendor/bryanjhv/slim-session/src/Slim/Middleware/Session.php on line 112

Do you really need to set session.gc_probability = 1 ??

**Comment by bryanjhv** [comment] 2017-07-06 22:01
Submit a pull-request if having another way to solve it.
Closing as a duplicate of #5, #6, #7, #14.

**Closed as completed by bryanjhv** 2017-07-06 22:01 UTC
Labels: duplicate
