### ISSUE TITLE
How does this package protect cookies?

### ISSUE THREAD

**Issue by carc1n0gen** [bryanjhv/slim-session#31] opened 2018-01-03 18:22 UTC
I was wondering what this package does to protect cookies.  Are they signed?

Is anything done to prevent tampering with cookies?

**Comment by bryanjhv** [comment] 2018-01-04 15:33
Duplicate of #21.

Hint: it doesn't. You must register a custom session handler.

**Closed as completed by bryanjhv** 2018-01-04 15:33 UTC
Labels: duplicate
