### ISSUE TITLE
Session reset

### ISSUE THREAD

**Issue by FvsJ101** [bryanjhv/slim-session#44] opened 2019-09-30 11:20 UTC
Hi, I have followed the instruction as in the read me file no session_* anything anywhere but in the middleware.

When I do a slim 4 redirect is seems to reset the session data. So nothing I set in my controllers outside of my middlewareis kept for the new view.
![middlewaresetup](https://user-images.githubusercontent.com/12259096/65874035-11c83600-e385-11e9-9d07-68f2b74c3f86.JPG)
![redirect](https://user-images.githubusercontent.com/12259096/65874036-1260cc80-e385-11e9-82a6-d27498e01578.JPG)
![result](https://user-images.githubusercontent.com/12259096/65874039-1260cc80-e385-11e9-8787-9813fb77242f.JPG)

**Comment by bryanjhv** [comment] 2019-09-30 19:32
Please try adding Session middleware first.
I'll try to do a demo showing that redirects don't clear session unless another package (or own code) calls any `session_*` functions.

**Comment by FvsJ101** [comment] 2019-10-01 14:47
Hi Bryan,

You mean add it last as slim is LIFO? or other why?

Regards
Michael

**Comment by FvsJ101** [comment] 2019-10-01 17:16
Hi Bryan,

Tried both ways, still not working.

Regards
Michael

**Comment by bryanjhv** [comment] 2019-10-02 02:50
Can't reproduce it.

```json
{
    "require": {
        "slim/slim": "^4.2",
        "bryanjhv/slim-session": "^4.0",
        "slim/psr7": "^0.5.0"
    }
}
```

```php
require 'vendor/autoload.php';

use Slim\Factory\AppFactory;
use SlimSession\Helper as SessionHelper;
use Slim\Middleware\Session as SlimSession;
use Psr\Http\Message\ResponseInterface as Response;
use Psr\Http\Message\ServerRequestInterface as Request;

$app = AppFactory::create();
$app->add(new SlimSession([
    'name' => 'example',
    'autorefresh' => true,
    'lifetime' => '30 minutes',
    'secure' => false,
    'httponly' => true,
]));

$app->get('/', function (Request $request, Response $response) {
    $helper = new SessionHelper();
    $helper->set('hello', 'world');

    $response->getBody()->write(json_encode($_SESSION));
    return $response
              ->withHeader('Content-Type', 'application/json')
              ->withStatus(200);
});

$app->get('/dest', function (Request $request, Response $response) {
    $response->getBody()->write(json_encode($_SESSION));
    return $response
              ->withHeader('Content-Type', 'application/json')
              ->withStatus(200);
});

$app->get('/redir', function (Request $request, Response $response) {
    return $response
              ->withHeader('Location', '/dest')
              ->withStatus(302);
});

$app->addErrorMiddleware(true, true, true);

$app->run();
```

Closing for lack of information and code to test.
Feel free to open a new issue adding that. Thanks.

**Closed as completed by bryanjhv** 2019-10-02 02:50 UTC
Labels: invalid
